import aiSolutionsImage from "@/public/images/ai-solutions.png";
import { BlogPost } from "@/types/blog";

export const blogPosts: BlogPost[] = [
  // Comprehensive blog posts with full MDX content
  {
    id: "future-of-generative-ai",
    title: "The Future of Generative AI: Trends and Predictions",
    description: "Explore the cutting-edge trends in generative AI and discover how they're reshaping business operations across every industry in 2025 and beyond.",
    excerpt: "Generative AI is no longer a futuristic concept—it's here, transforming how businesses operate. Explore the latest trends, real-world applications, and predictions for the future.",
    date: "January 22, 2025",
    readTime: "12 min read",
    author: {
      name: "Dr. Sarah Mitchell",
      role: "AI Research Director",
      avatar: "",
    },
    category: "AI Trends",
    image: aiSolutionsImage,
    slug: "future-of-generative-ai",
    tags: ["Generative AI", "Trends", "Innovation"],
  },
  {
    id: "ai-implementation-guide",
    title: "AI Implementation Guide: From Strategy to Production",
    description: "A comprehensive 6-phase roadmap for successfully implementing AI solutions in your organization, from initial strategy to production deployment.",
    excerpt: "Implementing AI successfully requires more than just technology—it requires a structured approach. Learn our proven 6-phase methodology.",
    date: "January 25, 2025",
    readTime: "15 min read",
    author: {
      name: "Michael Chen",
      role: "VP of AI Implementation",
      avatar: "",
    },
    category: "Implementation",
    image: aiSolutionsImage,
    slug: "ai-implementation-guide",
    tags: ["Implementation", "Strategy", "Best Practices"],
  },
  {
    id: "ai-roi-business-case",
    title: "Measuring AI ROI: Building a Compelling Business Case",
    description: "Learn how to quantify AI investment returns and build data-driven business cases that secure stakeholder buy-in and funding.",
    excerpt: "Securing AI project funding requires clear ROI calculations. Learn frameworks, real examples, and templates for building compelling business cases.",
    date: "January 22, 2025",
    readTime: "18 min read",
    author: {
      name: "Jennifer Rodriguez",
      role: "Chief Financial Strategist",
      avatar: "",
    },
    category: "Business Strategy",
    image: aiSolutionsImage,
    slug: "ai-roi-business-case",
    tags: ["ROI", "Business Case", "Finance"],
  },
  {
    id: "data-preparation-for-ai",
    title: "Data Preparation for AI: The Foundation of Success",
    description: "Master the critical but often overlooked process of preparing your data for AI implementation. Learn strategies for data collection, cleaning, and quality assurance.",
    excerpt: "Data preparation consumes 50-70% of AI project timelines. Learn how to do it right with our comprehensive 5-stage framework.",
    date: "January 29, 2025",
    readTime: "20 min read",
    author: {
      name: "Dr. Aisha Okonkwo",
      role: "Chief Data Officer",
      avatar: "",
    },
    category: "Data Science",
    image: aiSolutionsImage,
    slug: "data-preparation-for-ai",
    tags: ["Data Preparation", "Data Quality", "Best Practices"],
  },
  {
    id: "ai-ethics-guide",
    title: "A Comprehensive Guide to AI Ethics in Enterprise",
    description: "Navigate the complex landscape of AI ethics with our comprehensive guide covering bias mitigation, transparency, and responsible AI practices.",
    excerpt: "As AI becomes more prevalent in business decisions, understanding and implementing ethical AI practices is crucial for sustainable success.",
    date: "January 20, 2025",
    readTime: "14 min read",
    author: {
      name: "Priya Patel",
      role: "AI Ethics Director",
      avatar: "",
    },
    category: "AI Ethics",
    image: aiSolutionsImage,
    slug: "ai-ethics-guide",
    tags: ["AI Ethics", "Responsible AI", "Governance"],
  },
  {
    id: "ai-customer-service",
    title: "Transforming Customer Service with AI: A Complete Guide",
    description: "Discover how AI is revolutionizing customer service operations, from chatbots to sentiment analysis and predictive support.",
    excerpt: "Learn how leading companies are using AI to deliver exceptional customer experiences while reducing costs and improving efficiency.",
    date: "January 18, 2025",
    readTime: "16 min read",
    author: {
      name: "David Kim",
      role: "Lead Data Scientist",
      avatar: "",
    },
    category: "Customer Experience",
    image: aiSolutionsImage,
    slug: "ai-customer-service",
    tags: ["Customer Service", "AI Chatbots", "Automation"],
  },
];
